version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 9999:3000
    volumes:
      - /app/node_modules
      - .:/app
    command: [ "npm", "start" ]
  react-app-tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: [ "npm", "test" ]
networks:
  default:
    external:
      name: localdev
